name: Psychtoolbox-3
url: http://psychtoolbox.org
permalink:  /:title.html
pygments: false
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-titles-from-headings

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: :as_char
  toc_levels: 1..5
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  # smart_quotes:  ["apos", "apos", "ldquo", "rdquo"]
  use_coderay: false
  # input: GFM

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false

defaults:
  -
    scope:
      path: "" # empty string for all files
      type: pages
    values:
      layout: "page"
  -
    scope:
      path: "" # empty string for all files
      type: posts
    values:
      layout: "post"
      categories: "news"
      is_post: true
